### ISSUE TITLE
commented java file

### ISSUE THREAD

**Issue by HaleyHu** [onchainDNA/onchain-java#6]
In the file InterfaceEngine.java & ScriptEngine.java, there is only one code: `package OnChain.Core.Scripts;`, and the other code is commented. when I export project to a jar file, I will failed because of:
Class files on classpath not found or not accessible for: 'antshares-java/src/OnChain/Core/Scripts/InterfaceEngine.java'
  Class files on classpath not found or not accessible for: 'antshares-java/src/OnChain/Core/Scripts/ScriptEngine.java'

So, Maybe you should drop the java file directly or leave a empty java class. like that:
`
package OnChain.Core.Scripts;
public class InterfaceEngine{}
`

**Comment by tssqzr** [comment]
Thanks for your advice, I'll deal immediately.

**Comment by tssqzr** [comment]
Thank you for advice, I' ll deal with it immediately

**Comment by tssqzr** [comment]
@HaleyHu 
Thank you for advice, I' ll deal with it immediately
